create table if not exists public.commercial_leads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  lead_type text not null,
  name text not null,
  phone text,
  email text,
  company_name text,
  participants integer,
  preferred_date date,
  contact_preference text,
  budget_range text,
  objective text,
  notes text,
  status text not null default 'NUEVO',
  source text not null default 'WEB_APP'
);

create index if not exists commercial_leads_created_at_idx on public.commercial_leads (created_at desc);
create index if not exists commercial_leads_status_idx on public.commercial_leads (status);
create index if not exists commercial_leads_type_idx on public.commercial_leads (lead_type);

alter table public.commercial_leads enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'commercial_leads' and policyname = 'commercial_leads_insert_public'
  ) then
    create policy commercial_leads_insert_public
    on public.commercial_leads
    for insert
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'commercial_leads' and policyname = 'commercial_leads_select_public'
  ) then
    create policy commercial_leads_select_public
    on public.commercial_leads
    for select
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'commercial_leads' and policyname = 'commercial_leads_update_public'
  ) then
    create policy commercial_leads_update_public
    on public.commercial_leads
    for update
    using (true)
    with check (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'commercial_leads' and policyname = 'commercial_leads_delete_public'
  ) then
    create policy commercial_leads_delete_public
    on public.commercial_leads
    for delete
    using (true);
  end if;
end $$;
